-- =====================================================================
-- AgroControl · V1 · Creación completa del esquema PostgreSQL
-- Proyecto 16 · Programación Aplicada 2026-2
-- Ejecutar conectado como: agrocontrol_admin / base agrocontrol
-- Crea el schema "agrocontrol" con 18 tablas + 1 vista (bitácora por parcela).
-- Orden de creación respetando dependencias (Clase 05, Paso 12).
-- =====================================================================

SELECT current_user AS usuario_actual, current_database() AS base_actual;

CREATE SCHEMA IF NOT EXISTS agrocontrol;
SET search_path TO agrocontrol, public;

-- ---------------------------------------------------------------------
-- BLOQUE A · Identidad y catálogos base
-- ---------------------------------------------------------------------

-- 1. usuario
CREATE TABLE usuario (
    usuario_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(60)  NOT NULL,
    email            VARCHAR(160) NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    nombre_completo  VARCHAR(160) NOT NULL,
    activo           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_username_no_vacio CHECK (btrim(username) <> '')
);

-- 2. rol
CREATE TABLE rol (
    rol_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(40)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  TEXT         NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo),
    CONSTRAINT ck_rol_codigo CHECK (codigo IN
        ('ADMINISTRADOR','JEFE_CAMPO','OPERARIO','ALMACENERO','SUPERVISOR'))
);

-- 3. usuario_rol (puente N:M usuario <-> rol)
CREATE TABLE usuario_rol (
    usuario_rol_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT      NOT NULL,
    rol_id          BIGINT      NOT NULL,
    asignado_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo          BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_rol_id),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_usuario_rol_rol     FOREIGN KEY (rol_id)     REFERENCES rol (rol_id),
    CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id)
);

-- 4. unidad_medida · RN-07 (las unidades son explícitas y controladas)
CREATE TABLE unidad_medida (
    unidad_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo      VARCHAR(15) NOT NULL,
    nombre      VARCHAR(60) NOT NULL,
    magnitud    VARCHAR(20) NOT NULL,
    activo      BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_unidad_medida PRIMARY KEY (unidad_id),
    CONSTRAINT uq_unidad_medida_codigo UNIQUE (codigo),
    CONSTRAINT ck_unidad_medida_magnitud CHECK (magnitud IN
        ('MASA','VOLUMEN','SUPERFICIE','CONTEO','TIEMPO'))
);

-- ---------------------------------------------------------------------
-- BLOQUE B · Predios y parcelas (núcleo de los capítulos 01-07)
-- ---------------------------------------------------------------------

-- 5. predio  (ENTIDAD PADRE del par 1:N)
CREATE TABLE predio (
    predio_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(30)  NOT NULL,
    nombre       VARCHAR(120) NOT NULL,
    municipio    VARCHAR(100) NULL,
    ubicacion    VARCHAR(220) NULL,
    responsable_id BIGINT     NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_predio PRIMARY KEY (predio_id),
    CONSTRAINT fk_predio_responsable FOREIGN KEY (responsable_id) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_predio_codigo UNIQUE (codigo),
    CONSTRAINT ck_predio_codigo_no_vacio CHECK (btrim(codigo) <> '')
);

-- 6. parcela  (ENTIDAD DEPENDIENTE del par 1:N)
CREATE TABLE parcela (
    parcela_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    predio_id             BIGINT        NOT NULL,
    codigo                VARCHAR(30)   NOT NULL,
    nombre                VARCHAR(120)  NOT NULL,
    superficie_hectareas  NUMERIC(10,4) NOT NULL,
    tipo_suelo            VARCHAR(30)   NULL,
    estado                VARCHAR(20)   NOT NULL DEFAULT 'DISPONIBLE',
    observacion           TEXT          NULL,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_parcela PRIMARY KEY (parcela_id),
    CONSTRAINT fk_parcela_predio FOREIGN KEY (predio_id) REFERENCES predio (predio_id),
    -- Unicidad CONTEXTUAL: el código se repite entre predios, no dentro del mismo
    CONSTRAINT uq_parcela_predio_codigo UNIQUE (predio_id, codigo),
    CONSTRAINT ck_parcela_estado CHECK (estado IN
        ('DISPONIBLE','EN_CAMPANA','EN_DESCANSO','INACTIVA')),
    CONSTRAINT ck_parcela_superficie CHECK (superficie_hectareas > 0),
    CONSTRAINT ck_parcela_codigo_no_vacio CHECK (btrim(codigo) <> '')
);

-- 7. cultivo
CREATE TABLE cultivo (
    cultivo_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo           VARCHAR(30)  NOT NULL,
    nombre           VARCHAR(100) NOT NULL,
    variedad         VARCHAR(100) NULL,
    ciclo_dias       INTEGER      NULL,
    unidad_cosecha_id BIGINT      NOT NULL,
    activo           BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_cultivo PRIMARY KEY (cultivo_id),
    CONSTRAINT fk_cultivo_unidad FOREIGN KEY (unidad_cosecha_id) REFERENCES unidad_medida (unidad_id),
    CONSTRAINT uq_cultivo_codigo UNIQUE (codigo),
    CONSTRAINT ck_cultivo_ciclo CHECK (ciclo_dias IS NULL OR ciclo_dias > 0)
);

-- ---------------------------------------------------------------------
-- BLOQUE C · Campañas y labores · RN-01, RN-02, RN-03
-- ---------------------------------------------------------------------

-- 8. campana
CREATE TABLE campana (
    campana_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo          VARCHAR(30) NOT NULL,
    parcela_id      BIGINT      NOT NULL,
    cultivo_id      BIGINT      NOT NULL,
    fecha_inicio    DATE        NOT NULL,
    fecha_fin_prevista DATE     NOT NULL,
    fecha_cierre    DATE        NULL,
    estado          VARCHAR(20) NOT NULL DEFAULT 'PLANIFICADA',
    responsable_id  BIGINT      NOT NULL,
    observacion     TEXT        NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_campana PRIMARY KEY (campana_id),
    CONSTRAINT fk_campana_parcela FOREIGN KEY (parcela_id) REFERENCES parcela (parcela_id),
    CONSTRAINT fk_campana_cultivo FOREIGN KEY (cultivo_id) REFERENCES cultivo (cultivo_id),
    CONSTRAINT fk_campana_responsable FOREIGN KEY (responsable_id) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_campana_codigo UNIQUE (codigo),
    CONSTRAINT ck_campana_estado CHECK (estado IN
        ('PLANIFICADA','ACTIVA','FINALIZADA','CANCELADA')),
    CONSTRAINT ck_campana_fechas CHECK (fecha_fin_prevista > fecha_inicio),
    CONSTRAINT ck_campana_cierre CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_inicio)
);

-- 9. labor · RN-02 (pertenece a una campaña, y la parcela se obtiene por ella)
CREATE TABLE labor (
    labor_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campana_id      BIGINT       NOT NULL,
    codigo          VARCHAR(30)  NOT NULL,
    tipo            VARCHAR(25)  NOT NULL,
    descripcion     TEXT         NULL,
    fecha_planificada DATE       NOT NULL,
    fecha_inicio_real TIMESTAMPTZ NULL,
    fecha_fin_real  TIMESTAMPTZ  NULL,
    estado          VARCHAR(20)  NOT NULL DEFAULT 'PLANIFICADA',
    motivo_cancelacion TEXT      NULL,
    created_by      BIGINT       NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_labor PRIMARY KEY (labor_id),
    CONSTRAINT fk_labor_campana FOREIGN KEY (campana_id) REFERENCES campana (campana_id),
    CONSTRAINT fk_labor_created_by FOREIGN KEY (created_by) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_labor_campana_codigo UNIQUE (campana_id, codigo),
    CONSTRAINT ck_labor_tipo CHECK (tipo IN
        ('PREPARACION','SIEMBRA','FERTILIZACION','RIEGO','CONTROL_MALEZA',
         'CONTROL_PLAGA','PODA','MONITOREO','COSECHA','OTRA')),
    CONSTRAINT ck_labor_estado CHECK (estado IN
        ('PLANIFICADA','ASIGNADA','EN_EJECUCION','COMPLETADA','CANCELADA')),
    CONSTRAINT ck_labor_fechas_reales CHECK
        (fecha_fin_real IS NULL OR fecha_inicio_real IS NULL OR fecha_fin_real >= fecha_inicio_real),
    CONSTRAINT ck_labor_cancelacion CHECK
        (estado <> 'CANCELADA' OR motivo_cancelacion IS NOT NULL),
    CONSTRAINT ck_labor_completada CHECK
        (estado <> 'COMPLETADA' OR fecha_fin_real IS NOT NULL)
);

-- 10. asignacion_labor · RN-05 (el operario sólo reporta lo asignado)
CREATE TABLE asignacion_labor (
    asignacion_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    labor_id       BIGINT      NOT NULL,
    operario_id    BIGINT      NOT NULL,
    asignado_por   BIGINT      NOT NULL,
    asignado_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_asignacion_labor PRIMARY KEY (asignacion_id),
    CONSTRAINT fk_asignacion_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT fk_asignacion_operario FOREIGN KEY (operario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_asignacion_asignado_por FOREIGN KEY (asignado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_asignacion_labor_operario UNIQUE (labor_id, operario_id)
);

-- ---------------------------------------------------------------------
-- BLOQUE D · Insumos · RN-04, RN-07
-- ---------------------------------------------------------------------

-- 11. insumo
CREATE TABLE insumo (
    insumo_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo         VARCHAR(30)   NOT NULL,
    nombre         VARCHAR(140)  NOT NULL,
    tipo           VARCHAR(25)   NOT NULL,
    unidad_id      BIGINT        NOT NULL,
    stock_actual   NUMERIC(14,3) NOT NULL DEFAULT 0,
    stock_minimo   NUMERIC(14,3) NOT NULL DEFAULT 0,
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_insumo PRIMARY KEY (insumo_id),
    CONSTRAINT fk_insumo_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_medida (unidad_id),
    CONSTRAINT uq_insumo_codigo UNIQUE (codigo),
    CONSTRAINT ck_insumo_tipo CHECK (tipo IN
        ('SEMILLA','FERTILIZANTE','FITOSANITARIO','COMBUSTIBLE','HERRAMIENTA','OTRO')),
    CONSTRAINT ck_insumo_stock CHECK (stock_actual >= 0),          -- RN-04
    CONSTRAINT ck_insumo_stock_minimo CHECK (stock_minimo >= 0)
);

-- 12. movimiento_insumo
CREATE TABLE movimiento_insumo (
    movimiento_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    insumo_id         BIGINT        NOT NULL,
    tipo              VARCHAR(20)   NOT NULL,
    cantidad          NUMERIC(14,3) NOT NULL,
    saldo_resultante  NUMERIC(14,3) NOT NULL,
    usuario_id        BIGINT        NOT NULL,
    labor_id          BIGINT        NULL,
    motivo            VARCHAR(200)  NULL,
    ocurrido_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_movimiento_insumo PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento_insumo_insumo FOREIGN KEY (insumo_id) REFERENCES insumo (insumo_id),
    CONSTRAINT fk_movimiento_insumo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_movimiento_insumo_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT ck_movimiento_insumo_tipo CHECK (tipo IN
        ('ENTRADA','SALIDA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO')),
    CONSTRAINT ck_movimiento_insumo_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_movimiento_insumo_saldo CHECK (saldo_resultante >= 0),   -- RN-04
    CONSTRAINT ck_movimiento_insumo_labor CHECK (tipo <> 'SALIDA' OR labor_id IS NOT NULL)
);

-- 13. consumo_labor · RN-04, RF-11
CREATE TABLE consumo_labor (
    consumo_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    labor_id       BIGINT        NOT NULL,
    insumo_id      BIGINT        NOT NULL,
    movimiento_id  BIGINT        NOT NULL,
    cantidad       NUMERIC(14,3) NOT NULL,
    unidad_id      BIGINT        NOT NULL,
    registrado_por BIGINT        NOT NULL,
    registrado_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_consumo_labor PRIMARY KEY (consumo_id),
    CONSTRAINT fk_consumo_labor_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT fk_consumo_labor_insumo FOREIGN KEY (insumo_id) REFERENCES insumo (insumo_id),
    CONSTRAINT fk_consumo_labor_movimiento FOREIGN KEY (movimiento_id) REFERENCES movimiento_insumo (movimiento_id),
    CONSTRAINT fk_consumo_labor_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_medida (unidad_id),
    CONSTRAINT fk_consumo_labor_usuario FOREIGN KEY (registrado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_consumo_labor_movimiento UNIQUE (movimiento_id),
    CONSTRAINT ck_consumo_labor_cantidad CHECK (cantidad > 0)       -- RN-07
);

-- ---------------------------------------------------------------------
-- BLOQUE E · Bitácora, incidencias y cosecha
-- ---------------------------------------------------------------------

-- 14. bitacora_campo · RF-08, RF-15
CREATE TABLE bitacora_campo (
    bitacora_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parcela_id    BIGINT      NOT NULL,
    campana_id    BIGINT      NULL,
    labor_id      BIGINT      NULL,
    tipo_registro VARCHAR(20) NOT NULL,
    observacion   TEXT        NOT NULL,
    registrado_por BIGINT     NOT NULL,
    registrado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_bitacora_campo PRIMARY KEY (bitacora_id),
    CONSTRAINT fk_bitacora_parcela FOREIGN KEY (parcela_id) REFERENCES parcela (parcela_id),
    CONSTRAINT fk_bitacora_campana FOREIGN KEY (campana_id) REFERENCES campana (campana_id),
    CONSTRAINT fk_bitacora_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT fk_bitacora_usuario FOREIGN KEY (registrado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_bitacora_tipo CHECK (tipo_registro IN
        ('OBSERVACION','AVANCE_LABOR','CONSUMO','INCIDENCIA','COSECHA')),
    CONSTRAINT ck_bitacora_observacion CHECK (btrim(observacion) <> '')
);

-- 15. incidencia · RN-08 (siempre vinculada a parcela/campaña/labor)
CREATE TABLE incidencia (
    incidencia_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parcela_id     BIGINT      NOT NULL,
    campana_id     BIGINT      NULL,
    labor_id       BIGINT      NULL,
    tipo           VARCHAR(25) NOT NULL,
    severidad      VARCHAR(20) NOT NULL,
    descripcion    TEXT        NOT NULL,
    estado         VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
    reportado_por  BIGINT      NOT NULL,
    reportado_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    cerrada_at     TIMESTAMPTZ NULL,
    CONSTRAINT pk_incidencia PRIMARY KEY (incidencia_id),
    CONSTRAINT fk_incidencia_parcela FOREIGN KEY (parcela_id) REFERENCES parcela (parcela_id),
    CONSTRAINT fk_incidencia_campana FOREIGN KEY (campana_id) REFERENCES campana (campana_id),
    CONSTRAINT fk_incidencia_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT fk_incidencia_usuario FOREIGN KEY (reportado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_incidencia_tipo CHECK (tipo IN
        ('PLAGA','ENFERMEDAD','CLIMA','MAQUINARIA','PERSONAL','OTRA')),
    CONSTRAINT ck_incidencia_severidad CHECK (severidad IN ('BAJA','MEDIA','ALTA')),
    CONSTRAINT ck_incidencia_estado CHECK (estado IN ('ABIERTA','EN_REVISION','CERRADA')),
    CONSTRAINT ck_incidencia_cierre CHECK (estado <> 'CERRADA' OR cerrada_at IS NOT NULL)
);

-- 16. cosecha · RN-06, RN-07
CREATE TABLE cosecha (
    cosecha_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    campana_id       BIGINT        NOT NULL,
    fecha            DATE          NOT NULL,
    cantidad         NUMERIC(14,3) NOT NULL,
    unidad_id        BIGINT        NOT NULL,
    calidad          VARCHAR(20)   NULL,
    observacion      TEXT          NULL,
    registrado_por   BIGINT        NOT NULL,
    registrado_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_cosecha PRIMARY KEY (cosecha_id),
    CONSTRAINT fk_cosecha_campana FOREIGN KEY (campana_id) REFERENCES campana (campana_id),
    CONSTRAINT fk_cosecha_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_medida (unidad_id),
    CONSTRAINT fk_cosecha_usuario FOREIGN KEY (registrado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_cosecha_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_cosecha_calidad CHECK (calidad IS NULL OR calidad IN
        ('PRIMERA','SEGUNDA','TERCERA','DESCARTE'))
);

-- ---------------------------------------------------------------------
-- BLOQUE F · Trazabilidad · RN-09, RF-18
-- ---------------------------------------------------------------------

-- 17. historial_estado_labor · RN-03
CREATE TABLE historial_estado_labor (
    historial_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    labor_id         BIGINT       NOT NULL,
    estado_anterior  VARCHAR(20)  NULL,
    estado_nuevo     VARCHAR(20)  NOT NULL,
    motivo           VARCHAR(200) NULL,
    cambiado_por     BIGINT       NOT NULL,
    cambiado_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_historial_estado_labor PRIMARY KEY (historial_id),
    CONSTRAINT fk_historial_labor FOREIGN KEY (labor_id) REFERENCES labor (labor_id),
    CONSTRAINT fk_historial_usuario FOREIGN KEY (cambiado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_historial_estado_nuevo CHECK (estado_nuevo IN
        ('PLANIFICADA','ASIGNADA','EN_EJECUCION','COMPLETADA','CANCELADA')),
    CONSTRAINT ck_historial_estado_anterior CHECK (estado_anterior IS NULL OR estado_anterior IN
        ('PLANIFICADA','ASIGNADA','EN_EJECUCION','COMPLETADA','CANCELADA'))
);

-- 18. auditoria
CREATE TABLE auditoria (
    auditoria_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id    BIGINT      NULL,
    entidad       VARCHAR(60) NOT NULL,
    entidad_id    BIGINT      NULL,
    accion        VARCHAR(40) NOT NULL,
    detalle       JSONB       NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_auditoria PRIMARY KEY (auditoria_id),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- ---------------------------------------------------------------------
-- RN-09 · No se elimina el historial de campañas terminadas
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_impedir_borrado_historico()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'RN-09: los registros de % no se pueden eliminar', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER trg_bitacora_no_delete
    BEFORE DELETE ON bitacora_campo
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_movimiento_insumo_no_delete
    BEFORE DELETE ON movimiento_insumo
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_historial_labor_no_delete
    BEFORE DELETE ON historial_estado_labor
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_auditoria_no_delete
    BEFORE DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

-- RN-09 · Una campaña FINALIZADA no vuelve atrás ni se borra
CREATE OR REPLACE FUNCTION fn_proteger_campana_finalizada()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'RN-09: no se elimina una campaña (%), su historial debe conservarse', OLD.codigo;
    END IF;
    IF OLD.estado = 'FINALIZADA' AND NEW.estado <> 'FINALIZADA' THEN
        RAISE EXCEPTION 'RN-09: la campaña % ya está finalizada y no puede reabrirse', OLD.codigo;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_campana_protegida
    BEFORE UPDATE OR DELETE ON campana
    FOR EACH ROW EXECUTE FUNCTION fn_proteger_campana_finalizada();

-- ---------------------------------------------------------------------
-- RF-15 · Bitácora consolidada por parcela (vista, no tabla duplicada)
-- ---------------------------------------------------------------------
CREATE VIEW vw_bitacora_parcela AS
SELECT b.registrado_at,
       p.predio_id,
       pa.parcela_id,
       pa.codigo        AS codigo_parcela,
       c.codigo         AS campana,
       l.codigo         AS labor,
       b.tipo_registro,
       b.observacion,
       us.username      AS registrado_por
FROM bitacora_campo b
JOIN parcela pa  ON pa.parcela_id = b.parcela_id
JOIN predio p    ON p.predio_id = pa.predio_id
LEFT JOIN campana c ON c.campana_id = b.campana_id
LEFT JOIN labor l   ON l.labor_id = b.labor_id
JOIN usuario us  ON us.usuario_id = b.registrado_por;

-- ---------------------------------------------------------------------
-- Índices justificados
-- ---------------------------------------------------------------------
CREATE INDEX idx_parcela_predio          ON parcela (predio_id);            -- listar parcelas por predio (Cap. 07)
CREATE INDEX idx_parcela_estado          ON parcela (estado);
CREATE INDEX idx_campana_parcela         ON campana (parcela_id);           -- RN-01 ocupación por fechas
CREATE INDEX idx_campana_rango           ON campana (fecha_inicio, fecha_fin_prevista);
CREATE INDEX idx_labor_campana           ON labor (campana_id);             -- RF-16 avance por campaña
CREATE INDEX idx_labor_estado_fecha      ON labor (estado, fecha_planificada);
CREATE INDEX idx_asignacion_operario     ON asignacion_labor (operario_id); -- RF-06 agenda del operario
CREATE INDEX idx_movimiento_insumo_fecha ON movimiento_insumo (insumo_id, ocurrido_at);
CREATE INDEX idx_consumo_labor_labor     ON consumo_labor (labor_id);
CREATE INDEX idx_bitacora_parcela_fecha  ON bitacora_campo (parcela_id, registrado_at); -- RF-15
CREATE INDEX idx_incidencia_parcela      ON incidencia (parcela_id, estado);
CREATE INDEX idx_cosecha_campana         ON cosecha (campana_id);
CREATE INDEX idx_auditoria_entidad       ON auditoria (entidad, entidad_id);

-- Verificación rápida: debe devolver 18
SELECT COUNT(*) AS cantidad_tablas
FROM information_schema.tables
WHERE table_schema = 'agrocontrol'
  AND table_type = 'BASE TABLE';
