spring.application.name=AgroControl

spring.datasource.url=${AGROCONTROL_DB_URL:jdbc:postgresql://localhost:5432/agrocontrol}
spring.datasource.username=${AGROCONTROL_DB_USER:postgres}
spring.datasource.password=${AGROCONTROL_DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
